# -*- coding: utf-8 -*-
"""Covid_data_scrapping

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pyGkDM8E_KsgzpiGLDabR13QYqGGjLd1
"""

import requests
import csv
from bs4 import BeautifulSoup

def get_soup(url):
    page = requests.get(url)
    # print(page.status_code)
    soup = BeautifulSoup(page.content, 'html.parser')
    return soup

def loop(a,b):
  for x in range(a,b):
    work=soup2[x]
    Country=work.find_all('td')[1].text
    Total_Cases=work.find_all('td')[2].text
    New_Cases=work.find_all('td')[3].text
    Total_Deaths=work.find_all('td')[4].text
    New_Deaths=work.find_all('td')[5].text
    Total_Recovered=work.find_all('td')[6].text
    New_Recovered=work.find_all('td')[7].text
    Active_Cases=work.find_all('td')[8].text
    Serious_Critical=work.find_all('td')[9].text
    Total_Cases_per_Million=work.find_all('td')[10].text
    Deaths_per_Million=work.find_all('td')[11].text
    Population=work.find_all('td')[14].text
    data=[Country,Total_Cases,New_Cases,Total_Deaths,New_Deaths,Total_Recovered,New_Recovered,Active_Cases,Serious_Critical,Total_Cases_per_Million,Deaths_per_Million,Population]
    writer.writerow(data)


covid_source='https://www.worldometers.info/coronavirus/'
soup1=get_soup(covid_source)  
soup1.prettify
soup2=soup1.find_all('tr',style_="")
work=soup2[9]
Country=work.find_all('td')[1].text
Total_Cases=work.find_all('td')[2].text
New_Cases=work.find_all('td')[3].text
Total_Deaths=work.find_all('td')[4].text
New_Deaths=work.find_all('td')[5].text
Total_Recovered=work.find_all('td')[6].text
New_Recovered=work.find_all('td')[7].text
Active_Cases=work.find_all('td')[8].text
Serious_Critical=work.find_all('td')[9].text
Total_Cases_per_Million=work.find_all('td')[10].text
Deaths_per_Million=work.find_all('td')[11].text
Population=work.find_all('td')[14].text

#print('Country='+Country+'\n'+'Total_Cases='+Total_Cases+'\n'+'New_Cases='+New_Cases+'\n'+'Total_Deaths='+Total_Deaths+'\n'+'New_Deaths='+New_Deaths+'\n'\
  #    +'Total_Recovered='+Total_Recovered+'\n'+'New_Recovered='+New_Recovered+'\n'+'Active_Cases='+Active_Cases+'\n'+'Serious_Critical='+Serious_Critical+'\n'\
 #     +'Total_Cases_per_Million='+Total_Cases_per_Million+'\n'+'Deaths_per_Million='+Deaths_per_Million+'\n'+'Population='+Population)

header=['Country','Total_Cases','New_Cases','Total_Deaths','New_Deaths','Total_Recovered','New_Recovered','Active_Cases','Serious_Critical','Total_Cases_per_Million','Deaths_per_Million','Population']


#present day range(9,231)
#yesterday range(250,472)
#day before yesterday range(490,712)

with open('countries_live_cases.csv', 'w', encoding='UTF8') as f: #for writing we use 'w'
   writer = csv.writer(f)
   writer.writerow(header)
   loop(9,231)

with open('countries_yesterday.csv', 'w', encoding='UTF8') as f: #for writing we use 'w'
   writer = csv.writer(f)
   writer.writerow(header)
   loop(250,472)

with open('countries_daybefore_yesterday.csv', 'w', encoding='UTF8') as f: #for writing we use 'w'
   writer = csv.writer(f)
   writer.writerow(header)
   loop(490,712)